name: Cypress Tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests and generate JSON reports
        run: |
          npx cypress run --reporter mochawesome --reporter-options reportDir=mochawesome-report,overwrite=false,html=false,json=true

      - name: Merge and generate single Mochawesome HTML report
        run: |
          npx mochawesome-merge mochawesome-report/*.json | npx mochawesome-report-generator --inline --reportDir mochawesome-report

      - name: Upload Mochawesome report HTML
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report/mochawesome.html
